### ISSUE TITLE
Add message to current request

### ISSUE THREAD

**Issue by roelvanduijnhoven** [zendframework/zend-mvc-plugin-flashmessenger#17]
I would like to be able to add a message to the FlashMessenger that is to be shown *this* request. 

Repeatedly I find myself missing this functionality. It _is_ supported in Rails and called `Flash.now`. I mention this because Rails is mentioned as a reference in the README.

My proposal would be:
* Introduce `addDirectMessage` with parameters `$message` and `$namespace`.
* Messages are truncated after request. Also when they aren't rendered at all.

Would be able to make a PR. But would like to know beforehand if such a thing is considered. Especially  given this repo looks a bit inactive ..

**Comment by froschdesign** [comment]
Look at these methods:

https://github.com/zendframework/zend-mvc-plugin-flashmessenger/blob/843654a029a19c38e0c3b2e940e59edec75c3e4f/src/FlashMessenger.php#L401

https://github.com/zendframework/zend-mvc-plugin-flashmessenger/blob/843654a029a19c38e0c3b2e940e59edec75c3e4f/src/FlashMessenger.php#L462

and more…

See also at the documentation: https://docs.zendframework.com/zend-mvc-plugin-flashmessenger/

**Comment by roelvanduijnhoven** [comment]
But there is no method to _add_ a message during the current request, right? Or at least it is not clear to me how I can do that.

**Comment by froschdesign** [comment]
> But there is no method to add a message during the current request, right?

`addMessage` is the correct usage.

**Comment by roelvanduijnhoven** [comment]
Thanks for helping out @froschdesign. Hope that I don't miss something obvious but I feel this is not sufficient. 

Let's get some code into this to clearify my point.

A Controller fires:
```php
public function doesNotRedirectAction() 
{
    $this->flashMessenger()->addMessage('Bla');
    return new ViewModel([]);
}
```

And I render in my layout using:
```
<?=$this->flashMessenger()->render()?>
```

Now the message I add to the flash message **will not show up** the first time I access the page.

I can fix that by using:

```
<?=$this->flashMessenger()->renderCurrent()?>
```

But the later **will not show** the flash messages that were set on a previous request but could not be rendered in the current request. Because we redirected after a flash:

```php
public function doesNotRedirectAction() 
{
    $this->flashMessenger()->addMessage('Bla');
    return $this->redirect()->toRoute(...);
}
```

A solution is to adapt the flash render logic to something like:
```php
/** @var \Zend\Mvc\Controller\Plugin\FlashMessenger $flashMessenger */
$flashMessenger = $this->flashMessenger();
$messages = array_merge(
    $flashMessenger->getMessages($namespace),
    $flashMessenger->getCurrentMessages($namespace)
);
$flashMessenger->clearCurrentMessages($namespace);
var_dump($message);
```

That code *does* function properly and solves my use-case. But:
* that code cannot run twice, as it removes the current messages. 
* would better be abstracted in the FlashMessenger component itself.

Any thoughts @froschdesign?

**Comment by alextech** [comment]
If you need message showing up multiple times, maybe you need to specify how many hops it should be present for? Are your namespaces different by any chance. There is a bug if you try to use different namespaces before all messages have expired.

**Comment by roelvanduijnhoven** [comment]
No it need to show it only once. But reliable.

So if a add a message to the current request, it should be rendered once the next the flash messenger is rendered. But there is no way to reliable do so when you want to deal with two cases a) message + redirect or b) message + viewmodel response => direct render.

**Comment by froschdesign** [comment]
@roelvanduijnhoven 
> But there is no way to reliable do so when you want to deal with two cases a) message + redirect or b) message + viewmodel response => direct render.

My suggestion: write a view helper for yourself. Merge the current messages and the messages from the previous request.

**Comment by roelvanduijnhoven** [comment]
Allrighty: will do so. Just thought this would be a valid use-case, and thus more happy could profit from this being in the repo.

**Comment by MatthiasKuehneEllerhold** [comment]
@roelvanduijnhoven wants to have a storage that store messages until they are retrieved.
Retrieving them in the current request? -> Delete
Not retrieving them in the current request? -> Keep for next request

The problem is that the flash messenger currently doesnt have this behaviour. It hard-deletes any message after X hops. Whether they were retrieved from the storage or not. (See `\Zend\Session\AbstractContainer::expireByHops()`). Well technically if a request never calls the constructor of the FlashMessenger-Container the hop count wouldnt decrement.

Implementing @roelvanduijnhoven suggestion would be an entirely new behaviour which would be fit for a new type of messenger. I'd be interested in that new messenger, it just wouldnt fit the current flash messenger idea.
