### ISSUE TITLE
Incomplete component documentation

### ISSUE THREAD

**Issue by rolandoisidoro** [zendframework/zend-mvc-plugin-flashmessenger#20]
Hi,

the official documentation for this component is incomplete:

- There's a link to a page for [Flash Messenger View Helper](https://docs.zendframework.com/zend-mvc-plugin-flashmessenger/flash-messenger-view-helper/), which returns 404;
- There's no documentation for the Flash Messenger Controller Plugin.

For reference, here are ZF2's documentation pages for:
- [Flash Messenger View Helper documentation](https://framework.zend.com/manual/2.4/en/modules/zend.view.helpers.flash-messenger.html);
- [Flash Messenger Controller Plugin](https://framework.zend.com/manual/2.4/en/modules/zend.mvc.plugins.html#zend-mvc-controller-plugins-flashmessenger)

Best regards,
Rolando Isidoro

**Comment by froschdesign** [comment]
> There's a link to a page for Flash Messenger View Helper, which returns 404;

This is a bug. See: #21 

> There's no documentation for the Flash Messenger Controller Plugin.

Mmmh, the documentation for the controller plugin was never ported.
