### ISSUE TITLE
zf2 problem

### ISSUE THREAD

**Issue by simoesp** [zendframework/zend-mvc-plugin-flashmessenger#4]
hello i cannot install the plugin via composer with zf2 framework always requiring zend-mvc 3

backwards version compatibility on any version ?

**Comment by simoesp** [comment]
solved by 
composer require zendframework/zend-mvc:2.7.10

**Comment by weierophinney** [comment]
This plugin is **bundled with v2 releases of zend-mvc**, which is why this component marks itself as a conflict with v2 releases. You only need to install this component if you are using zend-mvc v3 or above, as those releases were the first to remove the plugin from the default distribution.
