### ISSUE TITLE
Fatal Error calling isArray() in getMessages()

### ISSUE THREAD

**Issue by exptom** [zendframework/zend-mvc-plugin-flashmessenger#9]
I get this error when using the plugin:
`( ! ) Fatal error: Call to a member function toArray() on array in /vagrant/vendor/zendframework/zend-mvc-plugin-flashmessenger/src/FlashMessenger.php on line 300`

From what I can see, when the session is loaded back in the messages are populated as a plain array rather than an array object. 
I'm including this plugin in a zend-mvc v3 project.

This has been previously reported against zend-mvc: https://github.com/zendframework/zend-mvc/issues/73

**Comment by weierophinney** [comment]
Can you please provide some information on how to reproduce the issue, so we can write tests? Thanks!

**Comment by exptom** [comment]
I've spent some time trying to create a basic example that illustrates this bug but so far have not succeeded. I've create a project using the skeleton app and included the flashmessenger plugin but cannot reproduce this bug which leads me to think that it must be when it is used in combination with non-default session storage. My app that is encountering the bug stores sessions in the Db using DbTableGateway savehandler. 
I'm going to see if I can split that code out into my skeleton app to recreate the bug.

**Comment by m0rg** [comment]
i am encountering this bug, while my colleague with the exact same application on his machine does not. very strange, i really dont know what differs on our systems, it runs in a docker container with the same dockerfile.

i add the messages in another module, and the controller passes the instance of it to the method handling it:

```
class IndexController extends AbstractActionController {

...
function loginAction() {
...
$response =  $this->authModel->login($postData['username'], $postData['password'], $this->url()->fromRoute('home'), $this->url()->fromRoute('index'), $this->flashMessenger());
...
```

in authModel->login i do

`if($messenger instanceof \Zend\Mvc\Plugin\FlashMessenger\FlashMessenger){
                $messenger->addSuccessMessage('auth.loginsuccess');
`

this function returns a Response object with a redirect. the page is loaded after that, but on the next page load i get the above described error.

I also noticed that there are two FlashMessenger entries in the session - one unter __ZF, and one under FlashMessenger.

$_SESSION[FlashMessenger] =>
Zend\Stdlib\ArrayObject Object ( [storage:protected] => Array ( ) [flag:protected] => 2 [iteratorClass:protected] => ArrayIterator [protectedProperties:protected] => Array ( [0] => storage [1] => flag [2] => iteratorClass [3] => protectedProperties ) )

$_SESSION[__ZF][FlashMessenger] => Array ( [EXPIRE_HOPS] => Array ( [hops] => 0 [ts] => 1479659452.5797 ) ) )

Feel free to ask for more details.

Edit:
Now i know what differs from our Configuration. He hasnt enabled the SanSessionToolbar!
And the SanSessionToolbar does
$container = new Container('FlashMessenger');
which appearantly is ignoring custom session implementations
FUUUCK!

**Comment by m0rg** [comment]
try using SanSessionToolbar to reproduce it.

**Comment by exptom** [comment]
Aha! The SanSessionToolbar is the common factor here.
I couldn't reproduce it when trying to build a test case but I use the SanSessionToolbar in my dev environment. Thanks for your help pinpointing this m0rg

**Comment by exptom** [comment]
@samsonasik do you have any ideas as to why this might be happening?

**Comment by samsonasik** [comment]
Please create issue at https://github.com/samsonasik/SanSessionToolbar/issues with steps to reproduce the issue, or sample repo that reproduce the issue, thanks ;)

**Comment by samsonasik** [comment]
@exptom @m0rg anyway, I've just tagged SanSessionToolbar 1.0.5 that bring FlashMessenger container from its plugin, not individual new container. 

Please give a try, and if you have issue, please create issue at https://github.com/samsonasik/SanSessionToolbar/issues  . Thanks ;)

**Comment by m0rg** [comment]
Thanks, that fixed it for me. Thank you, samsonasik
Edit: or not. sorry
still persists appearantly

**Comment by exptom** [comment]
I'm also still having this problem.

**Comment by froschdesign** [comment]
@exptom @mOrg
With or without `SanSessionToolbar`?

**Comment by exptom** [comment]
@froschdesign With `SanSessionToolbar` enabled.

**Comment by froschdesign** [comment]
@samsonasik 
Is this error in your `SanSessionToolbar` or is this an error of the flashmessenger plugin?

Thanks!

**Comment by samsonasik** [comment]
I can't reproduce it. any minimal reproduce-able repository I can try ?

**Comment by samsonasik** [comment]
@exptom also, please submit an issue at https://github.com/samsonasik/SanSessionToolbar/issues with minimal reproducable repo so I can check if you sure it is an SanSessionToolbar bug. Thank you.

**Comment by samsonasik** [comment]
@m0rg @exptom I finally can reproduce the issue with idempotent call. I've tagged  SanSessionToolbar 1.0.6 for it.

Please composer update and make sure `SanSessionToolbar` in the last entry in config/modules.config.php or config/application.config.php.

**Comment by exptom** [comment]
@samsonasik 1.0.6 appears to have fixed the issue. Thank you so much for your help! :smile:
